# Generated by Django 5.2.6 on 2025-09-18 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposaldetails',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disposal_details', to='jobs_main_app.job'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='jobs',
            field=models.ManyToManyField(blank=True, related_name='equipment', to='jobs_main_app.job'),
        ),
        migrations.AlterField(
            model_name='hauler',
            name='jobs',
            field=models.ManyToManyField(blank=True, related_name='haulers', to='jobs_main_app.job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs_main_app.customer'),
        ),
    ]
