# Generated by Django 5.2.6 on 2025-09-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_main_app', '0002_alter_disposaldetails_job_alter_equipment_jobs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hauler',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='hauler',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
