# Generated by Django 5.2.6 on 2025-09-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_main_app', '0003_hauler_email_hauler_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
