# Generated by Django 5.2.6 on 2025-09-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_main_app', '0004_customer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hauler',
            name='jobs',
        ),
        migrations.AddField(
            model_name='job',
            name='haulers',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='jobs_main_app.hauler'),
        ),
    ]
